### ISSUE TITLE
Lisp nesting exceeds ‘max-lisp-eval-depth’ error

### ISSUE THREAD

**Issue by galeo** [swift-emacs/swift-mode#169]
When trying to call function`jit-lock-fontify-now`, this errror will occur.

<details><summary>Here is the backtrace log:</summary>
<pre>
Debugger entered--Lisp error: (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
  #f(compiled-function (matched names) #<bytecode 0x1fef426f2869>)(nil #<hash-table equal 79/97 0x1fef42810a21>)
  #f(compiled-function (elt) #<bytecode 0x1fef426f2b95>)(#<hash-table equal 79/97 0x1fef42810a21>)
  mapc(#f(compiled-function (elt) #<bytecode 0x1fef426f2b95>) (#<hash-table equal 79/97 0x1fef42810a21> #<hash-table equal 484/487 0x1fef42830eb1>))
  seq-do(#f(compiled-function (elt) #<bytecode 0x1fef426f2b95>) (#<hash-table equal 79/97 0x1fef42810a21> #<hash-table equal 484/487 0x1fef42830eb1>))
  seq-reduce(#f(compiled-function (matched names) #<bytecode 0x1fef426f2869>) (#<hash-table equal 79/97 0x1fef42810a21> #<hash-table equal 484/487 0x1fef42830eb1>) nil)
  #f(compiled-function (pos limit) #<bytecode 0x1fef42f477f9>)(7758 18354)
  swift-mode:font-lock-match-expr(18354 #f(compiled-function (pos limit) #<bytecode 0x1fef42f477f9>))
  swift-mode:font-lock-match-expr(18354 #f(compiled-function (pos limit) #<bytecode 0x1fef42f477f9>))
  swift-mode:font-lock-match-expr(18354 #f(compiled-function (pos limit) #<bytecode 0x1fef42f477f9>))
  swift-mode:font-lock-match-expr(18354 #f(compiled-function (pos limit) #<bytecode 0x1fef42f477f9>))
  ...
  ....[lots of same lines]...
  ....
  swift-mode:font-lock-match-expr(18354 #f(compiled-function (pos limit) #<bytecode 0x1fef42f477f9>))
  swift-mode:font-lock-match-expr(18354 #f(compiled-function (pos limit) #<bytecode 0x1fef42f477f9>))
  swift-mode:font-lock-match-expr(18354 #f(compiled-function (pos limit) #<bytecode 0x1fef42f477f9>))
  swift-mode:font-lock-match-builtin-enum-case-names(18354)
  font-lock-fontify-keywords-region(1519 18354 nil)
  font-lock-default-fontify-region(1519 18354 nil)
  font-lock-fontify-region(1519 18354)
  #f(compiled-function (fun) #<bytecode 0x1fef446dac55>)(font-lock-fontify-region)
  run-hook-wrapped(#f(compiled-function (fun) #<bytecode 0x1fef446dac55>) font-lock-fontify-region)
  jit-lock--run-functions(1519 18354)
  jit-lock-fontify-now()</pre>
</details>

Restart emacs, and when it tries to restore the previously opened swift file, it will freeze. By executing the ~C-g~ key serveral times, it will return to normal, and there will be the following output in `*Messages*` buffer:

```
Error during redisplay: (internal--syntax-propertize 1442) signaled (quit)
Error during redisplay: (internal--syntax-propertize 4000) signaled (quit)
Error during redisplay: (internal--syntax-propertize 6042) signaled (quit)
Error during redisplay: (internal--syntax-propertize 8248) signaled (quit)
Error during redisplay: (internal--syntax-propertize 10546) signaled (quit)
Error during redisplay: (internal--syntax-propertize 12685) signaled (quit)
Error during redisplay: (internal--syntax-propertize 14710) signaled (quit)
Error during redisplay: (internal--syntax-propertize 16795) signaled (quit)
```

**Comment by taku0** [comment]
Thank you for reporting.  Fixed by 5597eafa55934c67185e627c362663753f695865, hopefully.  
The fix will soon be deployed to MELPA in few days.  Could you try it from MELPA or `master` branch?

**Comment by galeo** [comment]
Thanks for the fix. It works well when trying to call `jit-lock-fontify-now`. However, emacs still freezes when trying to restore the previously opened swift file at startup. Act as before, the `*Messages*` buffer will have a slight difference in output:

```
Error during redisplay: (internal--syntax-propertize 1437) signaled (quit)
Error during redisplay: (internal--syntax-propertize 3799) signaled (quit)
Error during redisplay: (internal--syntax-propertize 5863) signaled (quit)
Error during redisplay: (internal--syntax-propertize 7962) signaled (quit)
Error during redisplay: (internal--syntax-propertize 10068) signaled (quit)
Error during redisplay: (internal--syntax-propertize 12188) signaled (quit)
Error during redisplay: (internal--syntax-propertize 14213) signaled (quit)
Error during redisplay: (internal--syntax-propertize 16298) signaled (quit)
```

The swift file used for testing is the same. I don't know how to debug this problem.

**Comment by taku0** [comment]
I guess font-locking is just slow.  I have no idea how to improve it.
